export const MOCK_AUTH = {
  email: 'abc@gmail.com',
  password: '123456',
};

export const PROJECTS = [
  {
    id: 'p1',
    name: 'Skyline Tower Phase 1',
    status: 'In Progress',
    startDate: '2024-01-15',
    location: 'Downtown Metro',
    color: 'blue',
  },
  {
    id: 'p2',
    name: 'Green Valley Residential',
    status: 'Planning',
    startDate: '2024-04-01',
    location: 'Suburban Heights',
    color: 'gray',
  },
  {
    id: 'p3',
    name: 'Bridge Reconstruction - Sector 7',
    status: 'On Hold',
    startDate: '2024-02-10',
    location: 'Industrial District',
    color: 'yellow',
  },
  {
    id: 'p4',
    name: 'Industrial Park Warehouse',
    status: 'Completed',
    startDate: '2023-11-20',
    location: 'East Side',
    color: 'green',
  },
  {
    id: 'p5',
    name: 'Grand Central Plaza',
    status: 'In Progress',
    startDate: '2024-03-01',
    location: 'Central Hub',
    color: 'blue',
  },
  {
    id: 'p6',
    name: 'Ocean View Apartments',
    status: 'Planning',
    startDate: '2024-05-15',
    location: 'Coastal Road',
    color: 'gray',
  },
  {
    id: 'p7',
    name: 'Metro Line Extension',
    status: 'In Progress',
    startDate: '2024-01-05',
    location: 'Underground Sector 4',
    color: 'blue',
  },
  {
    id: 'p8',
    name: 'Solar Power Plant',
    status: 'Planning',
    startDate: '2024-06-01',
    location: 'Western Desert',
    color: 'gray',
  },
  {
    id: 'p9',
    name: 'City IT Park',
    status: 'In Progress',
    startDate: '2024-02-20',
    location: 'Tech Corridor',
    color: 'blue',
  },
  {
    id: 'p10',
    name: 'Heritage Mall Renovation',
    status: 'On Hold',
    startDate: '2023-12-10',
    location: 'Old Town',
    color: 'yellow',
  },
  {
    id: 'p11',
    name: 'Smart City Hospital',
    status: 'In Progress',
    startDate: '2024-03-15',
    location: 'Medical Zone',
    color: 'blue',
  },
  {
    id: 'p12',
    name: 'Riverside Walkway',
    status: 'Completed',
    startDate: '2023-10-01',
    location: 'Riverbank South',
    color: 'green',
  },
];

export const WEATHER_OPTIONS = ['Sunny', 'Cloudy', 'Rainy', 'Stormy', 'Windy'];
